<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">
  <xacro:property name="width_1" value="0.004"/>
  <xacro:property name="body_len" value="0.1"/>
  <xacro:property name="box_param" value="0.5"/>
  <xacro:property name="box_param1" value="0.25"/>
  <xacro:property name="spawn_point" value="3.0"/>
  <xacro:property name="radius" value="0.101"/>
  <xacro:property name="small" value="0.005"/>
  <xacro:property name="load_mass" value="2.0"/>
  <xacro:property name="friction" value="0.02"/>
  <xacro:property name="damping1" value="0.5"/>
  <xacro:property name="effort_joint" value="1000"/>
  <xacro:property name="large" value="100"/>
  <xacro:property name="inertia_rope1" value="0.01"/>
  <xacro:property name="inertia_rope2" value="0.02"/>
  <xacro:property name="mass_rope" value="0.1"/>
  <xacro:property name="mass_link" value="0.001"/>
  <xacro:property name="inertia_link" value="0.01"/>
  <xacro:property name="velocity_joint" value="300"/>
  <xacro:property name="load_inertia" value="0.0"/>
  <link name="world"/>
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${box_param} ${3*box_param} ${box_param}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${box_param} ${3*box_param} ${box_param}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${spawn_point}"/>
    </collision>
    <inertial>
      <mass value="${small}"/>
      <inertia ixx="${small}" ixy="0.0" ixz="0.0" iyy="${small}" iyz="0.0" izz="${small}"/>
      <origin rpy="0 0 0" xyz="0 0 ${spawn_point}"/>
    </inertial>
  </link>
  <link name="leg1">
    <visual>
      <geometry>
        <box size="${box_param} ${box_param1}  ${spawn_point+box_param/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-spawn_point/2}"/>
    </visual>
    <collision>
      <geometry>
        <box size="${box_param} ${box_param1}  ${spawn_point+box_param/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-spawn_point/2}"/>
    </collision>
    <inertial>
      <mass value="${large}"/>
      <inertia ixx="${large}" ixy="0.0" ixz="0.0" iyy="${large}" iyz="0.0" izz="${large}"/>
      <origin rpy="0 0 0" xyz="0 ${3*box_param} ${-spawn_point/2}"/>
    </inertial>
  </link>
  <link name="leg2">
    <visual>
      <geometry>
        <box size="${box_param} ${-box_param1}  ${spawn_point+box_param/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-spawn_point/2}"/>
    </visual>
    <collision>
      <geometry>
        <box size="${box_param} ${-box_param1} ${spawn_point+box_param/2}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${spawn_point/2}"/>
    </collision>
    <inertial>
      <mass value="${large}"/>
      <inertia ixx="${large}" ixy="0.0" ixz="0.0" iyy="${large}" iyz="0.0" izz="${large}"/>
      <origin rpy="0 0 0" xyz="0 ${-3*box_param} ${-spawn_point/2}"/>
    </inertial>
  </link>
  <link name="rope_1">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_2">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_3">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_4">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_5">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_6">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_7">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_8">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_9">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="rope_10">
    <visual>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${body_len}" radius="${width_1}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </collision>
    <inertial>
      <mass value="${mass_rope}"/>
      <inertia ixx="${inertia_rope1}" ixy="0.0" ixz="0.0" iyy="${inertia_rope1}" iyz="0.0" izz="${inertia_rope2}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len/2}"/>
    </inertial>
  </link>
  <link name="load">
    <visual>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-radius}"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-radius}"/>
    </collision>
    <inertial>
      <mass value="${load_mass}"/>
      <inertia ixx="${load_inertia}" ixy="0.0" ixz="0.0" iyy="${load_inertia}" iyz="0.0" izz="${load_inertia}"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-radius}"/>
    </inertial>
  </link>
  <joint name="world_base_link" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${spawn_point}"/>
  </joint>
  <joint name="leg1_base_link" type="fixed">
    <parent link="base_link"/>
    <child link="leg1"/>
    <origin xyz="0 ${3*box_param/2+box_param1/2} ${box_param/4}"/>
  </joint>
  <joint name="leg2_base_link" type="fixed">
    <parent link="base_link"/>
    <child link="leg2"/>
    <origin xyz="0 ${-(3*box_param/2+box_param1/2)} ${box_param/4}"/>
  </joint>
  <link name="rope1Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope1Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="base_link_to_rope1Psi" type="revolute">
    <parent link="base_link"/>
    <child link="rope1Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-box_param/2}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope1Psi_to_rope1Theta" type="revolute">
    <parent link="rope1Psi"/>
    <child link="rope1Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope1Theta_to_rope_1" type="revolute">
    <parent link="rope1Theta"/>
    <child link="rope_1"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope2Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope2Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_1_to_rope2Psi" type="revolute">
    <parent link="rope_1"/>
    <child link="rope2Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope2Psi_to_rope2Theta" type="revolute">
    <parent link="rope2Psi"/>
    <child link="rope2Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope2Theta_to_rope_2" type="revolute">
    <parent link="rope2Theta"/>
    <child link="rope_2"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope3Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope3Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_2_to_rope3Psi" type="revolute">
    <parent link="rope_2"/>
    <child link="rope3Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope3Psi_to_rope3Theta" type="revolute">
    <parent link="rope3Psi"/>
    <child link="rope3Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope3Theta_to_rope_3" type="revolute">
    <parent link="rope3Theta"/>
    <child link="rope_3"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope4Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope4Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_3_to_rope4Psi" type="revolute">
    <parent link="rope_3"/>
    <child link="rope4Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope4Psi_to_rope4Theta" type="revolute">
    <parent link="rope4Psi"/>
    <child link="rope4Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope4Theta_to_rope_4" type="revolute">
    <parent link="rope4Theta"/>
    <child link="rope_4"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope5Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope5Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_4_to_rope5Psi" type="revolute">
    <parent link="rope_4"/>
    <child link="rope5Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope5Psi_to_rope5Theta" type="revolute">
    <parent link="rope5Psi"/>
    <child link="rope5Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope5Theta_to_rope_5" type="revolute">
    <parent link="rope5Theta"/>
    <child link="rope_5"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope6Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope6Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_5_to_rope6Psi" type="revolute">
    <parent link="rope_5"/>
    <child link="rope6Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope6Psi_to_rope6Theta" type="revolute">
    <parent link="rope6Psi"/>
    <child link="rope6Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope6Theta_to_rope_6" type="revolute">
    <parent link="rope6Theta"/>
    <child link="rope_6"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope7Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope7Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_6_to_rope7Psi" type="revolute">
    <parent link="rope_6"/>
    <child link="rope7Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope7Psi_to_rope7Theta" type="revolute">
    <parent link="rope7Psi"/>
    <child link="rope7Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope7Theta_to_rope_7" type="revolute">
    <parent link="rope7Theta"/>
    <child link="rope_7"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope8Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope8Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_7_to_rope8Psi" type="revolute">
    <parent link="rope_7"/>
    <child link="rope8Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope8Psi_to_rope8Theta" type="revolute">
    <parent link="rope8Psi"/>
    <child link="rope8Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope8Theta_to_rope_8" type="revolute">
    <parent link="rope8Theta"/>
    <child link="rope_8"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope9Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope9Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_8_to_rope9Psi" type="revolute">
    <parent link="rope_8"/>
    <child link="rope9Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope9Psi_to_rope9Theta" type="revolute">
    <parent link="rope9Psi"/>
    <child link="rope9Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope9Theta_to_rope_9" type="revolute">
    <parent link="rope9Theta"/>
    <child link="rope_9"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope10Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope10Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_9_to_rope10Psi" type="revolute">
    <parent link="rope_9"/>
    <child link="rope10Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope10Psi_to_rope10Theta" type="revolute">
    <parent link="rope10Psi"/>
    <child link="rope10Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope10Theta_to_rope_10" type="revolute">
    <parent link="rope10Theta"/>
    <child link="rope_10"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <link name="rope11Theta">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <link name="rope11Psi">
    <inertial>
      <mass value="${mass_link}"/>
      <inertia ixx="${inertia_link}" ixy="0.0" ixz="0.0" iyy="${inertia_link}" iyz="0.0" izz="${inertia_link}"/>
    </inertial>
  </link>
  <joint name="rope_10_to_rope11Psi" type="revolute">
    <parent link="rope_10"/>
    <child link="rope11Psi"/>
    <origin rpy="0.0 0.0 0.0" xyz="0 0 ${-body_len}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope11Psi_to_rope11Theta" type="revolute">
    <parent link="rope11Psi"/>
    <child link="rope11Theta"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/2}" upper="${pi/2}" velocity="${velocity_joint}"/>
  </joint>
  <joint name="rope11Theta_to_load" type="revolute">
    <parent link="rope11Theta"/>
    <child link="load"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping1}" friction="${friction}"/>
    <limit effort="${effort_joint}" lower="${-pi/16}" upper="${pi/16}" velocity="${velocity_joint}"/>
  </joint>
  <gazebo reference="rope_1">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rope_2">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="rope_3">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rope_4">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="rope_5">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rope_6">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="rope_7">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rope_8">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="rope_9">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="rope_10">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="load">
    <material>Gazebo/Red</material>
  </gazebo>
</robot>
